# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-21 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20180521_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
