# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-20 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(max_length=30, unique=True),
        ),
    ]
